### ISSUE TITLE
Build failure with gcc-12

### ISSUE THREAD

**Issue by ALTracer** [zeldin/fx3lafw#3]
This does not compile with GNU ARM Toolchain 12.2.Rel1
https://github.com/zeldin/fx3lafw/blob/a141e8e90cfcfde82fa74b9570ae3df40a324d07/bsp/usb.c#L488-L499

```
arm-none-eabi-gcc -std=c11 -mcpu=arm926ej-s -mthumb-interwork -fno-pie -Wall -Wextra -Werror -g -Os -I. -MMD -MP -DPLL_FBDIV=20   -c -o usb.o bsp/usb.c
bsp/usb.c: In function 'Fx3UsbUsbCoreIsr':
bsp/usb.c:491:17: error: this 'else' clause does not guard... [-Werror=misleading-indentation]
  491 |                 else
      |                 ^~~~
bsp/usb.c:494:25: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'else'
  494 |                         (*Fx3UsbUserCallbacks->sutok)
      |                         ^
cc1: all warnings being treated as errors
```
It still builds with `gcc version 10.3.1 20210621 (release) (15:10.3-2021.07-4)`, but I can't verify how the ARM9 firmware works on the real hardware.
If the SetupData callback is meant to run at every OUT transfer, then suggested change:
```diff
diff --git a/bsp/usb.c b/bsp/usb.c
index 44e56e3..441c2b9 100644
--- a/bsp/usb.c
+++ b/bsp/usb.c
@@ -485,18 +485,18 @@ static void Fx3UsbUsbCoreIsr(void)
 
 		uint8_t req_type = setupdat0 >> 0;
 		uint16_t length = setupdat1 >> 	(48 - 32);
-		if ((req_type & FX3_USB_REQTYPE_DIR_MASK) == FX3_USB_REQTYPE_IN)
+		if ((req_type & FX3_USB_REQTYPE_DIR_MASK) == FX3_USB_REQTYPE_IN) {
 			/* IN transfer */
 			Fx3WriteReg32(FX3_DEV_EPI_XFER_CNT, length);
-		else
+		} else {
 			/* OUT transfer */
 			Fx3WriteReg32(FX3_DEV_EPO_XFER_CNT, length);
 			(*Fx3UsbUserCallbacks->sutok)
 			(req_type, setupdat0 >> FX3_PROT_SETUP_DAT_SETUP_REQUEST_SHIFT,
 			 setupdat0 >> FX3_PROT_SETUP_DAT_SETUP_VALUE_SHIFT,
 			 setupdat1 >> (FX3_PROT_SETUP_DAT_SETUP_INDEX_SHIFT - 32),
-			 length, FX3_USB_HIGH_SPEED); 
-		
+			 length, FX3_USB_HIGH_SPEED);
+		}
 	}
 	if (dev_ctrl_req & (1UL << 7))
 	{
```
Only the second set of curly braces for `else` clause is mandatory, but I like to put them on both branches of `if` for consistency, too.

Additionally, GCC-12.2 fails to link with this error:
```
arm-none-eabi-gcc -std=c11 -mcpu=arm926ej-s -mthumb-interwork -fno-pie -Wall -Wextra -Werror -g -Os -I. -MMD -MP -DPLL_FBDIV=20 -static -nostartfiles -T bsp/fx3.ld -Wl,-z,max-page-size=4096,-Map,fx3lafw.map -o fx3lafw.elf main.o usb.o gpif.o gctl.o gpio.o uart.o util.o dma.o irq.o cache.o vectors.o descriptors.o acquisition.o
/opt/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: warning: fx3lafw.elf has a LOAD segment with RWX permissions
/opt/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: /opt/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/lib/libg.a(libc_a-writer.o): in function `_write_r':
writer.c:(.text._write_r+0x24): undefined reference to `_write'
/opt/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: /opt/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/lib/libg.a(libc_a-closer.o): in function `_close_r':
closer.c:(.text._close_r+0x18): undefined reference to `_close'
/opt/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: /opt/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/lib/libg.a(libc_a-lseekr.o): in function `_lseek_r':
lseekr.c:(.text._lseek_r+0x24): undefined reference to `_lseek'
/opt/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: /opt/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/lib/libg.a(libc_a-readr.o): in function `_read_r':
readr.c:(.text._read_r+0x24): undefined reference to `_read'
collect2: error: ld returned 1 exit status
make: *** [GNUmakefile:28: fx3lafw.elf] Error 1
```
I suppose this is because of missing newlib-4 syscall stubs which were present in newlib-3. This is easily fixed by pulling nosys:
```diff
diff --git a/GNUmakefile b/GNUmakefile
index 114540b..7006e48 100644
--- a/GNUmakefile
+++ b/GNUmakefile
@@ -10,7 +10,7 @@ GENDEP = -MMD -MP
 DEFS = -DPLL_FBDIV=20
 
 CFLAGS = -std=c11 $(CGENFLAGS) $(WARN) $(OPTIMIZE) $(INCLUDE) $(GENDEP) $(DEFS)
-LDFLAGS = -static -nostartfiles -T bsp/fx3.ld -Wl,-z,max-page-size=4096,-Map,$(basename $@).map
+LDFLAGS = -static -nostartfiles --specs=nano.specs --specs=nosys.specs -T bsp/fx3.ld -Wl,-z,max-page-size=4096,-Map,$(basename $@).map
 
 VPATH = bsp
```
While we're at it, consider also testing with `--specs=nano.specs`. There are only 2 snprintf calls with hexadecimal format, no need to pull full double/float support, and flash size reduces from 48..64 KiB to just 16 KiB. Or is it RAM? The `bsp/fx3.ld` linkerscript is missing region bounds, but by referencing the MCU datasheet I figured the following:
```c
MEMORY
{
	itcm(rwx) : ORIGIN = 0x00000000, LENGTH = 0x4000  /* 16K */
	dtcm(rw ) : ORIGIN = 0x10000000, LENGTH = 0x2000  /* 8K */
	ram (rwx) : ORIGIN = 0x40000000, LENGTH = 0x40000 /* 256K */
}
```

**Comment by zeldin** [comment]
Hi.  Thanks for the report.  The code is correct as it is, there should be no braces.

The "misleading" indentation comes from cozycactus' USB2 support branch.  Looking at my working tree, it looks like I already fixed it but forgot to commit.  Oops.  😸

I also have an additional stub for `__stack_chk_fail` in my working tree, this might be what fixes the `_write` et al references.  I should commit that as well...

The code runs from RAM.  It's not a constraining resource at this point.

**Comment by zeldin** [comment]
I pushed my local changes now.
